nodeLinker: node-modules
enableGlobalCache: true

packageExtensions:
  react-day-picker@*:
    peerDependencies:
      react: "^18.2.0"
      date-fns: "^2.30.0"
  vaul@*:
    peerDependencies:
      react: "^18.2.0"
